apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce   # EBS 僅支援單一節點讀寫 (RWO)
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
