apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-cart
spec:
  schedule: "*/5 * * * *" # 為了 Demo 設為每5分鐘執行，實務上通常為每天半夜
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clean
            image: busybox:1.36
            command:
            - /bin/sh
            - -c
            - "echo 'Cleaning up expired carts (simulated)...' && sleep 5 && echo 'Done.'"
          restartPolicy: OnFailure
