apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zihaoc683-lang/eks-job-demo.git' # 自動替換為您的正確網址
    path: k8s/overlays/production
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # 這是修復 Drift (配置偏移) 的關鍵
