apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: web
          # 換成 podinfo，這是一個專為 K8s Demo 設計的視覺化應用
          image: stefanprodan/podinfo:6.2.3
          ports:
            - containerPort: 9898 # podinfo 預設跑在 9898
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
