apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: ecommerce-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898 # 對接 podinfo 的連接埠
  type: LoadBalancer
